name: Feature request
description: Ask for a new feature
title: "[Feat]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to ask for a new feature!
  - type: textarea
    id: what
    attributes:
      label: What do you want?
      description: A clear and concise description of what you would like to be able to do with our software.
    validations:
      required: true
  - type: textarea
    id: code-example
    attributes:
      label: A possible usage
      description: A code example which shows how to use this new feature.
      render: python
  - type: textarea
    id: code-implementation
    attributes:
      label: A possible implementation (if you have some ideas)
      description: A first idea of how this new feature could be implemented.
      render: python
  - type: textarea
    id: others
    attributes:
      label: Other informations
      description: Please feel free to provide any other information you feel may be useful for understanding and implementing this new feature.
