name: Question
description: Ask for clarification of any unclear points.
title: "[Question]: "
labels: ["question", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to ask a question here!
  - type: textarea
    id: what
    attributes:
      label: What do you want?
      description: A clear and concise description of what you would like to do
    validations:
      required: true
  - type: textarea
    id: code-example
    attributes:
      label: A possible usage (if relevant)
      description: A code example which shows what you would like to do
      render: python
