name: "PyEPRI-CI"

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.12, 3.13]
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.XX
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}	
    - name: Install PyEPRI (basic installation)
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Install PyEPRI ("torch-cpu" optional dependency, except for macos-13 runner)
      if: matrix.os != 'macos-13'
      run: |
        pip install ".[torch-cpu]"
